
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Apr 04 19:23:32 CEST 2017
//----------------------------------------------------

package plic.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int IDF = 26;
  public static final int TYP = 29;
  public static final int EGAL = 23;
  public static final int OU = 13;
  public static final int CLASS = 21;
  public static final int PLUS = 2;
  public static final int SUP = 8;
  public static final int STAT = 28;
  public static final int ALORS = 16;
  public static final int NON = 14;
  public static final int WRITE = 20;
  public static final int POINTVIRGULE = 19;
  public static final int MOINS = 3;
  public static final int INF = 9;
  public static final int PARFER = 7;
  public static final int SINON = 17;
  public static final int EOF = 0;
  public static final int MULT = 4;
  public static final int EGALEGAL = 10;
  public static final int DIV = 5;
  public static final int CONSTANTEBOOL = 25;
  public static final int SI = 15;
  public static final int ET = 12;
  public static final int error = 1;
  public static final int PAROUV = 6;
  public static final int CONSTANTECHAINE = 27;
  public static final int DIFF = 11;
  public static final int CONSTANTEINT = 24;
  public static final int FIN = 22;
  public static final int FINSI = 18;
}

